### ISSUE TITLE
Target Dummy

### ISSUE THREAD

**Issue by gyrodrill** [tylerjwatson/SEconomy#8]
Players can get coins from target dummy(item).
When player place a target dummy, hit it, and use a pickaxe to pick it, they will get lots of money.
Target Dummy will create a NPC (ID: 488) which have 1000 HP and SEconomy regard that hitting this NPC should get money. 
Is there some way to ignore it or some other solutions?

**Comment by Tygra** [comment]
{
		"TILEID": 378,
		"OverridenMoneyPerDamagePoint": 0.0
	},
